### ISSUE TITLE
משתנה גלובלי לא יעבוד כשיש כמה פונקציות שונות

### ISSUE THREAD

**Issue by erelsgl** [kggold4/programming-research-algorithms-ex1#1]
https://github.com/kggold4/programming-research-algorithms-assignments/blob/573bd68bd6b515f8a09db3ea90714cdcace3a308/Python/Ex2/q2/q2.py#L2

**Comment by kggold4** [comment]
issue fixed, created a class that memorized the last value instead of a global value
